FROM adoptopenjdk/openjdk8-openj9:jdk8u181-b13_openj9-0.9.0

COPY batch-processor/target/batch-processor-0.0.1-SNAPSHOT.jar /

ENTRYPOINT ["java", "-jar", "-Xshareclasses:cacheDir=/cache", "-Xscmx300M", "-Xquickstart", "batch-processor-0.0.1-SNAPSHOT.jar", "--run_type=short" ]