FROM adoptopenjdk/openjdk8-openj9:jdk8u181-b13_openj9-0.9.0

COPY batch-processor/target/batch-processor-0.0.1-SNAPSHOT.jar /

RUN /bin/bash -c 'java -Xshareclasses:verbose -Xscmx500M -Xquickstart -jar batch-processor-0.0.1-SNAPSHOT.jar --run_type=short &' ; sleep 15 ; ps aux | grep java | grep batch-processor | awk '{print $2}' | xargs kill -1

ENTRYPOINT ["java", "-jar", "-Xshareclasses", "-Xscmx500M", "-Xdump:directory=/coredump", "-Xdump:java:events=vmstart,file=test.txt", "-Xquickstart", "batch-processor-0.0.1-SNAPSHOT.jar", "--run_type=short" ]