FROM adoptopenjdk/openjdk8-openj9:latest

COPY batch-processor-0.0.1-SNAPSHOT.jar /

RUN /bin/bash -c 'java -Xshareclasses:cacheDir=/cache -Xscmx200M -jar batch-processor-0.0.1-SNAPSHOT.jar --run_type=medium &' ; sleep 60

ENTRYPOINT ["java",  "-Xshareclasses:cacheDir=/cache,readOnly", "-jar", "batch-processor-0.0.1-SNAPSHOT.jar", "--run_type=long" ]