FROM adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u172-b11-nightly

ENTRYPOINT ["java",  "-XX:JITaaSServer", "-Xjit:verbose={compilePerformance},verbose={jitaas},vlog=/output/vlog.jitserver,disableSuffixLogs"]