FROM adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u172-b11-nightly

COPY batch-processor/target/batch-processor-0.0.1-SNAPSHOT.jar /

ENTRYPOINT ["java", "-jar", "-Xnojit", "-Xnoaot", "-XX:JITaaSClient:server=172.0.0.1", "-XX:+UseContainerSupport", "batch-processor-0.0.1-SNAPSHOT.jar", "--run-type=medium" ]