FROM adoptopenjdk/openjdk8-openj9:jdk8u181-b13_openj9-0.9.0

COPY batch-processor-0.0.1-SNAPSHOT.jar /

ENTRYPOINT ["java", "-jar", "-Xtune:virtualized", "-Xshareclasses", "-Xscmx=50M", "-XX:+IdleTuningCompactOnIdle", "-XX:+IdleTuningGcOnIdle", "-XX:IdleTuningMinIdleWaitTime=5", "-XX:+UseContainerSupport", "batch-processor-0.0.1-SNAPSHOT.jar", "--spring.main.web-application-type=SERVLET" ]